version: "3.8"

services:
    frontend:
        build: client
        ports:
            - 3000:3000
    backend:
        build: server
        environment:
            CONNECTION_URL: mongodb://root:example@database/admin
        ports:
            - 5000:5000
    database:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        # restart: unless-stopped
